language: node_js
node_js: node
cache:
  directories:
    - node_modules
env: 
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: RxOF9tXuWNwA+s+oHxDZcdvs4w/4+CtgL3cshiV145XJ1hShlaywnh0Kyy4m5Q6C6Py67Tqe8H/AcskDDWj7/a3PDy5VjWC8vPDIAz2LzxUz9eVbXgz5tXxEoid3LbUZM4X/quT7QhRpIIBr/sh8vXymwq+23w8BJn209mHhCGH8Nz/P8mhbf2JIMKI0yZHOm6jdjK2LVpG1CIi2JrfQxztqkns/Zgsh2DabMDHggbl6inHMBJEC55oav00HQJ9pf5/PJgoV/6DVCrmpLGd/PymkWu7mxFAJiyQGR62frekEZ+2dC133aICEeCye90zTCm7uwMbeicijfh1W0ggtRHxxvq8FEwTUcqHAnRgo4uxdWC+1jGV7JmyiGtU4kzvKgr5d+YuL/7cagGEJhq0/wWF/B2KwqKrchhiAYGAU4PClcIW/9b4ZHmTS6Xnn0ACH5wayZCAoDlgvpKBWSun8XTSC9ZUG04Rcz+IrcONZzw/bTsA5VYI4Cr/waI8jQf1rug7Ms9wDa62Qn0bYCUtJmAkg1ev81Nl5hEGHp8DO6L8/mVD7QfYPsXhnyM8du6Hdh18xSiYPssIDO8hZKpfEQhgllfxqSSQsu6hbNoXln2wBvIe0ZY3yY2Fh+TeDRkxS6EvVOrmGg7Suhtlkhs3iMSjjh6ahsBLoja1q+z2GzNU=
  app: music-quiz-app
  on:
    repo: khriskempis/music-quiz-app
