language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: wFoQymOI9sd9pkP0eXmmw4tOlwCvoaL70W1w4XkhJSvQK/0a1B03XIFfrQ2o6eAPKS8ytp68GWtk2eNcBwwzyaYWyQR3WVLdUodAIhKHBIsSyY0yW/4+uzbnkMKuq1A/viQwHWJgH18L+k/vhGF5NVPdpgXo8/2fwmyvqzJvilNDRphQWBVV5LgTkur/Y5FeO8ukdhfpcYBxD60pkooM2uxG+FNE3abBZX9IhJzMx9wTxMaGXSEtkqUD0L6eC3VbVz9Bbz1Eumm7WsZekJN2L/OTut6QV2CmacaRs5n/VIJQSyHEbnEGD56YDD2RHojzKgA61bi+BNQ/QhchVsdFofZaBI/WBLHKAj7GBcKnWoIf5N92czl505dnPhiRv9ZfmsZf7Jn9pvhupbNC66XNvhug5PqvZzpPl/quhi7UnTbHJmwKh6h3+jazb7AD6Y26eikzh/McPPXNSJK3a2pq44fPjE4YRptnkjqgMtbV2L9xQSUbzlSDZoUVQm7uK45jlfsVCovHbUvFe7xlDHZb4TvJLuckZYrqyH9GpefBhRThfgBYcsoTasEHyCIYQuk4y6ozi57UhHW4VSRkdY4NSSt5xlaODiqfdfmaoidjr8ph6GWzELPyFywjjx56Fp8ANkEG4/+y2xKqLfSBMRmVEALIBFSys+RtzX4w8OuDXwI=
  app: stark-dusk-66511
  on:
    repo: khriskempis/music-quiz-app
